version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: flectra
      POSTGRES_USER: flectra
      POSTGRES_PASSWORD: flectra
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flectra-net

  flectra:
    image: flectrahq/flectra:2.0
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: flectra
      DB_PASSWORD: flectra
      DB_NAME: flectra
    ports:
      - "7073:7073"
    volumes:
      - flectra_data:/var/lib/flectra
    networks:
      - flectra-net

volumes:
  postgres_data:
  flectra_data:

networks:
  flectra-net:
