version: '2'
services:
  db:
    image: postgres:9.5
    user: root
    environment:
      - POSTGRES_PASSWORD=flectra
      - POSTGRES_USER=flectra
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  flectra2:
    image: flectra:2.0
    user: root
    depends_on:
      - db
    ports:
      - "10002:7073"
      - "20002:8072" # live chat
    tty: true
    command: --
#    command: flectra scaffold /mnt/extra-addons/test_module
    environment:
      - HOST=db
      - USER=flectra
      - PASSWORD=flectra
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/flectra
    restart: always             # run as a service
